### ISSUE TITLE
Question about Learning Curve plotting

### ISSUE THREAD

**Issue by PRijnbeek** [mi-erasmusmc/PatientLevelPrediction#4]
In the learning curve plotting function, where is x, trainAUC, testAUC defined?

see:
https://github.com/mi-erasmusmc/PatientLevelPrediction/blob/9a1de53b38b28aeb642ffe2f73a27cfe6de1a637/R/Plotting.R#L738

We also get these warnings from R CDM Check:

plotLearningCurve: no visible binding for global variable ‘x’
plotLearningCurve: no visible binding for global variable ‘trainAUC’
plotLearningCurve: no visible binding for global variable ‘testAUC’

**Comment by lhjohn** [comment]
The variables x, trainAUC and testAUC are the column names of the learning curve object that we provide to the plotting function. The implementation has been modified to avoid this warning.
